# Generated by Django 5.2.10 on 2026-03-16 12:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "payload",
                    models.JSONField(
                        help_text='Schema: {"schema_version": "1.0", "serial_number": "SN123456", "value": 5.2}'
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry",
                "db_table": "telemetry",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="idx_telemetry_device_time",
                    ),
                    models.Index(fields=["-timestamp"], name="idx_telemetry_timestamp"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["payload"], name="idx_telemetry_payload_gin"
                    ),
                ],
            },
        ),
    ]
