# Generated by Django 5.2.10 on 2026-03-16 12:45

import django.contrib.postgres.indexes
import telemetry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelemetrySchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Example: '1.0', '2.0'", max_length=50, unique=True
                    ),
                ),
                (
                    "validation_schema",
                    models.JSONField(
                        default=dict,
                        help_text="Official JSON Schema for validating incoming telemetry data.",
                        validators=[telemetry.models.validate_json_schema],
                    ),
                ),
                (
                    "transformation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Rules for normalizing telemetry data. Example: {"rename": {"val": "temperature"}}',
                        validators=[telemetry.models.validate_transformation_rules],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Telemetry Schemas",
                "db_table": "telemetry_schema",
            },
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device", models.UUIDField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "payload",
                    models.JSONField(
                        help_text='Schema: {"schema_version": "1.0", "serial_number": "SN123456", "value": 5.2}'
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry",
                "db_table": "telemetry",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="idx_telemetry_device_time",
                    ),
                    models.Index(fields=["-timestamp"], name="idx_telemetry_timestamp"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["payload"], name="idx_telemetry_payload_gin"
                    ),
                ],
            },
        ),
    ]
